version: '3.8'

services:
  backend:
    build:
      context: ../
    container_name: backend
    restart: always
    ports:
      - 9999:8000
    env_file:
      - ../.env
    depends_on: 
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file:
      - ../.env
    restart: always
    ports:
      - "6379:6379"
  
  celery:
    build:
      context: ../
    container_name: celery
    restart: always
    env_file:
      - ../.env
    command: ["/app/deploy/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: ../
    restart: always
    container_name: flower
    env_file:
      - ../.env
    command: ["/app/deploy/celery.sh", "flower"]
    depends_on:
      - redis
    ports:
      - "5555:5555"
